### ISSUE TITLE
Change notation of bit assignment

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#73]
Change notation of bit assignment to swap position of LSB and width.
This is to support bit assignment without LSB position on XLSX register map.

For backward compatibility, add a new configuration parameter to specify what is the first element of notation of bit assignment.

**Comment by cookacounty** [comment]
The SystemRDL spec is probably the best standard to follow:

https://www.accellera.org/images/downloads/standards/systemrdl/SystemRDL_2.0_Jan2018.pdf

![image](https://user-images.githubusercontent.com/3683155/109421700-615dc780-79a6-11eb-9497-7948cb9a77e9.png)

You do not need to explicitly set the LSB (its assumed you start at zero).

For example if I defined some fields

field_a [4]
field_b [4]

I would get registers

field_a at bits [3:0] and field_b at bits [7:4]


This makes it pretty nice because you can just put in the width of the fields you need and then the tool keeps track of the indexes. Then when generated the tool puts out the physical indexes and addresses.

**Comment by taichi-ishitani** [comment]
@cookacounty ,
Thank you for your comment!
Now, you can omit LSB specifications when you use register map specification written in Excel.

![image](https://user-images.githubusercontent.com/2922232/109437980-0e017d00-7a6b-11eb-821c-411b2585cb0d.png)

For this case, bit assignments of these bit fields are as followings:

* bit_field_0: [3:0]
* bit_field_1: [7:4]
* bit_field_2: [8]
